import '../img/svg-sprite/telegram.svg';
import '../img/svg-sprite/whatsapp.svg';
import '../img/svg-sprite/instagram.svg';
import '../img/svg-sprite/phone.svg';
import '../img/svg-sprite/email.svg';
import '../img/svg-sprite/globus.svg';
import '../img/svg-sprite/pdf.svg';
import '../img/svg-sprite/arrow.svg';
import '../img/svg-sprite/download.svg';
